services:
  - type: web
    name: deewid-landing-v3-laravel
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DATABASE_URL
        sync: false
      - key: APP_KEY
        sync: false
