services:
  - type: web
    name: deewid-landing-v3-laravel
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://deewid-landing-v3.adrielzimbril.com
      - key: DEEWID_APP_DOMAIN
        value: deewid-landing-v3.adrielzimbril.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DATABASE_URL
        value: ""
      - key: APP_KEY
        sync: false
      - key: RUN_MIGRATIONS
        value: "false"
      - key: DEEWID_BLOG_DATABASE_ENABLED
        value: "false"
